package pl.jw.mbank.common.dto;

// Generated 2010-02-05 19:13:45 by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Investment generated by hbm2java
 */
@Entity(name = "INVESTMENT")
@Table(name = "INVESTMENT", uniqueConstraints = @UniqueConstraint(columnNames = { "SFI_ID" }))
public class InvestmentData implements java.io.Serializable {

	private SfiData sfi;

	private int id;
	private BigDecimal units;
	private BigDecimal initialvalue;
	private Boolean isSimulation;

	public InvestmentData() {
	}

	public InvestmentData(BigDecimal units, BigDecimal initialvalue) {
		this.units = units;
		this.initialvalue = initialvalue;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne
	@JoinColumn(nullable = false)
	public SfiData getSfi() {
		return sfi;
	}

	public void setSfi(SfiData sfi) {
		this.sfi = sfi;
	}

	@Column(name = "UNITS", nullable = true, columnDefinition = "DECIMAL(18,3)", precision = 18, scale = 3)
	public BigDecimal getUnits() {
		return this.units;
	}

	public void setUnits(BigDecimal units) {
		this.units = units;
	}

	@Column(name = "INITIALVALUE", nullable = true, columnDefinition = "DECIMAL(18,3)", precision = 18, scale = 3)
	public BigDecimal getInitialvalue() {
		return this.initialvalue;
	}

	public void setInitialvalue(BigDecimal initialvalue) {
		this.initialvalue = initialvalue;
	}

	@Column(name = "Simulation", nullable = false)
	public Boolean isSimulation() {
		return isSimulation;
	}

	public void setSimulation(Boolean isSimulation) {
		this.isSimulation = isSimulation;
	}

	@Override
	public String toString() {
		return "InvestmentData [sfi=" + sfi + ", id=" + id + ", units=" + units + ", initialvalue=" + initialvalue
				+ ", isSimulation=" + isSimulation + "]";
	}

}
