package pl.jw.mbank.common.dto;

// Generated 2010-02-05 19:13:45 by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.sql.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Stockquotes generated by hbm2java
 */
@Entity(name = "STOCKQUOTES")
@Table(name = "STOCKQUOTES", uniqueConstraints = @UniqueConstraint(columnNames = { "SFI_ID", "DATE" }))
public class StockQuotesData implements java.io.Serializable {

	private int id;

	private Date date;
	private SfiData sfi;
	private BigDecimal value;
	private BigDecimal delta;

	public StockQuotesData() {
	}

	public StockQuotesData(SfiData sfiData, BigDecimal value, BigDecimal delta) {
		//		this.id = id;
		this.value = value;
		this.delta = delta;
	}

	@ManyToOne(cascade = { CascadeType.DETACH, CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH })
	@JoinColumn(nullable = false)
	public SfiData getSfi() {
		return sfi;
	}

	public void setSfi(SfiData sfi) {
		this.sfi = sfi;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "DATE", nullable = false)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "VALUE", nullable = false, columnDefinition = "DECIMAL(18,3)", precision = 18, scale = 3)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	@Column(name = "DELTA", nullable = false, columnDefinition = "DECIMAL(18,3)", precision = 18, scale = 3)
	public BigDecimal getDelta() {
		return this.delta;
	}

	public void setDelta(BigDecimal delta) {
		this.delta = delta;
	}

	@Override
	public String toString() {
		return "StockQuotesData [id=" + id + ", sfi=" + sfi + ", date=" + date + ", value=" + value + ", delta="
				+ delta + "]";
	}

}
